import dynamic from "next/dynamic";
import Head from "next/head";

const ContactUs = dynamic(() => import("@/components/contact-us/ContactUs"), {
  ssr: false,
});

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ContactUs />
      </div>
    </>
  );
};

export default Contact;
