import CoreBanner from "@/components/common/core-components/core-banner/CoreBanner";
import dynamic from "next/dynamic";
import Head from "next/head";

const ContactUs = dynamic(() => import("@/components/contact-us/ContactUs"), {
  ssr: false,
});

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <CoreBanner
          title="Contact Us"
          subtitle="Contact us"
          crumbOne="Home"
          crumbTwo="Contact Us"
        />
        <div className={"container-wrapper"}>
          <ContactUs />
        </div>
      </div>
    </>
  );
};

export default Contact;
