import Head from "next/head";
import styles from "../styles/Home.module.scss";
// import HeroSection from "@/components/home/hero-section/Hero";
import dynamic from "next/dynamic";

const DynamicHeroSection = dynamic(
  () => import("@/components/home/hero-section/Hero"),
  {
    ssr: false,
  }
);
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles["home-wrapper"]}>
          <DynamicHeroSection />
        </main>
      </div>
    </>
  );
}
